#@cartId=2E64A8B2-91BD-44F7-98FC-C67FE8B6F002
#@cartId=30347666-1749-4251-982c-6f59c029da5b
#@cartId=2c10a5a2-3a85-4a13-ba22-2fdaf9949f03
@productId=209984
@userId=12345
@sessionId=1234
@purchaseOrderId=2c10a5a2-3a85-4a13-9999-2fdaf9949f03

### Create cart with user-id and session-id cookie values
# @name createCart
POST http://localhost:5170/cart
Content-Type: application/json
Cookie: user-id={{userId}}; session-id={{sessionId}}

{
  "operatingChain": "OCSEELG"
}
###
@cartId={{createCart.response.body.data.id}}

### Query carts
GET http://localhost:5170/cart?operatingChain=OCSEELG&userId={{userId}}

### Get cart
GET http://localhost:5170/cart/{{cartId}}

### Add item to cart
POST http://localhost:5170/cart/{{cartId}}/items
Content-Type: application/json

{
  "operatingChain": "OCSEELG",
  "productId": "{{productId}}"
}

### Remove item from cart
DELETE http://localhost:5170/cart/{{cartId}}/items/{{productId}}

### Get cart
GET http://localhost:5170/cart/{{cartId}}

### Get changes for cart
GET http://localhost:5170/cart/{{cartId}}/changes

### Get logged in user cart
GET http://localhost:5170/cart

### Get cart 
GET http://localhost:5170/cart/{{cartId}}

### Increase quantity of item in cart
PUT http://localhost:5170/cart/{{cartId}}/items/{{productId}}
Content-Type: application/json

{
  "quantity": 3,
  "productId": "{{productId}}"
}

### Abandon cart
POST http://localhost:5170/cart/{{cartId}}/abandon

### Clear cart
POST http://localhost:5170/cart/{{cartId}}/clear

### Recover cart
POST http://localhost:5170/cart/{{cartId}}/recover

### Create purchase order
# @name createPurchaseOrder
POST http://localhost:5170/checkout
Content-Type: application/json

{
  "cartId": "{{cartId}}"
}
###
@purchaseOrderId={{createPurchaseOrder.response.body.data.id}}

### Add payment to purchase order
POST http://localhost:5170/checkout/{{purchaseOrderId}}/payment
Content-Type: application/json

{
  "transactionId": "txn_stripe_123456789",
  "paymentMethod": "Credit Card",
  "paymentProvider": "Stripe",
  "amount": 1900,
  "currency": "SEK",
  "processedAt": "2025-05-31T10:30:00Z",
  "status": "Completed"
}

### Get purchase order with payment
GET http://localhost:5170/checkout/{{purchaseOrderId}}