#@BASE_URL_LOCAL = http://localhost:8001
@BASE_URL_LOCAL = http://localhost:5170
@BASE_URL_AZURE = https://monostore-api.whiteground-32f83688.northeurope.azurecontainerapps.io
#@BASE_URL = {{BASE_URL_AZURE}}
@BASE_URL = {{BASE_URL_LOCAL}}

### Get a product
GET {{BASE_URL}}/product/OCSEELG/209984

### Sample dump request
POST {{BASE_URL}}/product/dump

### Sample sync request
POST {{BASE_URL}}/product/sync
Content-Type: application/json

< ./products_110.json

### Sample sync request
POST {{BASE_URL}}/product/sync
Content-Type: application/json

[
  {
    "OperatingChain": "OCSEELG",
    "Bulletpoint1": "",
    "Bulletpoint2": "",
    "Bulletpoint3": "",
    "Title": "Lightning kabel 2m Space Gray",
    "OperatingChainSpecificStatus": "30",
    "ShortDescription": "Champions lightning-kabel med kontakthöljen i aluminium och flätade kabel är det snyggaste och smidigaste sättet att ladda och synka din iPhone, iPad och iPod touch.",
    "IsBuyableOnline": false,
    "IsBuyableInternet": false,
    "IsBuyableCollectAtStore": false,
    "IsBuyableInStore": false,
    "ChainPriceAmount": null,
    "ChainPriceAmountExVat": null,
    "ActivePriceAmount": null,
    "ActivePriceAmountExVat": null,
    "CustomerClubPriceAmount": null,
    "CustomerClubPriceAmountExVat": null,
    "MarginPercentage": null,
    "Currency": null,
    "ManufacturerArticleNumber": "49231406",
    "Name": "Lightning cable 2m Space Gray",
    "ArticleType": "ZHAW",
    "Status": "65",
    "MainLogisticalFlow": "06",
    "ContentStatus": "30",
    "OnlineArticle": "02",
    "Planner": "",
    "StockControlCode": "1",
    "OEM": false,
    "Warranty": false,
    "VendorGroup": "0000800837",
    "GlobalTradeItemNumbers": [
      { "gtin": "7391091853549", "type": "PRI", "packaging_unit": "PCE" }
    ],
    "ProductType": "Lightning cable (Apple)",
    "Image": "https://www.elgiganten.se/image/dv_web_D180001002497843/209096/lightning-kabel-2m-space-gray.jpg",
    "ArticleAssignmentsBrandId": "12268",
    "ArticleAssignmentsBrandName": "Champion",
    "ArticleAssignmentsPTId": "PT1034",
    "ArticleAssignmentsPTName": "Lightning-kabel",
    "ArticleAssignmentsCGMId": "48735",
    "ArticleAssignmentsCGMName": "Charge & Sync Cables",
    "ArticleAssignmentsPFTId": null,
    "ArticleAssignmentsTemplateId": "10134",
    "BadgeUrl": "",
    "BadgeUrlB2B": "",
    "SavePrice": "false",
    "AdvertisingText": "This is more advertising text2",
    "AdvertisingTextB2B": "",
    "BeforePrice": null,
    "BeforePriceExVat": null,
    "Disclaimer": null,
    "SalesPoint": "",
    "SalesPointB2B": "",
    "BGradeTitle": null,
    "BGrade": null,
    "PresaleDate": null,
    "ReleaseDate": null,
    "AlwaysOnline": "",
    "ArticleOperatingChainAttributes": "null",
    "BuyAndTryDays": 0,
    "CollectAtStore": false,
    "CompetitionCharacter": "1",
    "CustomerType": "",
    "Discountable": true,
    "DisplayDate": null,
    "DisplayGrade": "IA",
    "HomeDelivery": "",
    "PresaleQuantity": "0.0",
    "ProviderCode": "",
    "ReadyToGo": "",
    "RefaktorVendor": null,
    "RetailFirstSalesDate": "2020-08-21T00:00:00Z",
    "ReturnPolicy": "",
    "ServiceType": "",
    "ShipToCustomer": "",
    "ShipToStore": "",
    "StockGrade": "IA",
    "SupplyOverride": "",
    "VendorArticleNumber": "",
    "WhlSaleFirstSalesDate": "2020-08-21T00:00:00Z",
    "WhlSaleSalesStatus": "ACT",
    "AverageRating": null,
    "TotalReviewCount": null,
    "ArticleNumber": "209096",
    "AvailableFastDelivery": false,
    "WholesaleStockFilled": null,
    "WholeSaleIncomingDate": null,
    "WholeSaleDisplayStock": null,
    "ProductURL": "https://www.elgiganten.se/product/tjanster-tillbehor/kablar-anslutning/lightning-kabel/lightning-kabel-2m-space-gray/209096",
    "ProductURLB2B": null,
    "ParentArticleNumber": "209096",
    "OnlineSalesStatus": "ACT",
    "MarketplaceOffers": [],
    "EnergyRating": null,
    "EnergyEfficiencyScaleMax": null,
    "EnergyEfficiencyScaleMin": null,
    "Attributes": [
      {
        "Name": "Produkttyp",
        "Purpose": "Navigator;Relevant for PIF",
        "Sequence": 100,
        "Value": "Lightning-kabel",
        "Structure": "Template",
        "Identifier": "31158",
        "Description": "",
        "PresetValueIdentifier": "52536",
        "DataType": "Character string"
      },
      {
        "Name": "Typ av kabel",
        "Purpose": "Navigator;Relevant for PIF",
        "Sequence": 102,
        "Value": "Lightning-kabel",
        "Structure": "Template",
        "Identifier": "31826",
        "Description": "",
        "PresetValueIdentifier": "62201",
        "DataType": "Character string"
      },
      {
        "Name": "Relevant for Accessories",
        "Purpose": "Internal Reporting",
        "Sequence": 2147483647,
        "Value": "Yes",
        "Structure": "CGM",
        "Identifier": "Article_2996339677458953",
        "Description": "",
        "PresetValueIdentifier": "Yes",
        "DataType": "Character string"
      },
      {
        "Name": "Relevant for B2B",
        "Purpose": "Internal Reporting",
        "Sequence": 2147483647,
        "Value": "No",
        "Structure": "CGM",
        "Identifier": "Article_2996339677458969",
        "Description": "",
        "PresetValueIdentifier": "No",
        "DataType": "Character string"
      },
      {
        "Name": "shopFilename",
        "Purpose": "",
        "Sequence": 2147483647,
        "Value": "mirakl-uiLDkg9U-",
        "Structure": null,
        "Identifier": "Article_2996339677458979",
        "Description": "",
        "PresetValueIdentifier": null,
        "DataType": "Character string"
      },
      {
        "Name": "Warranty responsibility",
        "Purpose": "",
        "Sequence": 2147483647,
        "Value": "No",
        "Structure": "Brand",
        "Identifier": "Article_2996339677459002",
        "Description": "",
        "PresetValueIdentifier": "NO",
        "DataType": "Logical value"
      },
      {
        "Name": "shopId",
        "Purpose": "",
        "Sequence": 2147483647,
        "Value": "10204",
        "Structure": null,
        "Identifier": "Article_2996339677459006",
        "Description": "",
        "PresetValueIdentifier": null,
        "DataType": "Character string"
      },
      {
        "Name": "importId",
        "Purpose": "",
        "Sequence": 2147483647,
        "Value": "63590",
        "Structure": null,
        "Identifier": "Article_2996339677459038",
        "Description": "",
        "PresetValueIdentifier": null,
        "DataType": "Character string"
      },
      {
        "Name": "OEM SKU",
        "Purpose": "",
        "Sequence": 2147483647,
        "Value": "No",
        "Structure": "Brand",
        "Identifier": "Article_2996339677459041",
        "Description": "",
        "PresetValueIdentifier": "NO",
        "DataType": "Logical value"
      },
      {
        "Name": "ItemCategory",
        "Purpose": "Defining attritbute",
        "Sequence": 2147483647,
        "Value": "ZMAR",
        "Structure": null,
        "Identifier": "ItemCategory",
        "Description": "",
        "PresetValueIdentifier": null,
        "DataType": "Character string"
      }
    ],
    "AltArticleNumber": "MP49231406",
    "KeyWords": [],
    "ArticleCategory": "",
    "BoxSize": "0002",
    "PTLevel0": "Tjänster & Tillbehör",
    "PTLevel1": "Kablar & Anslutning",
    "PTLowestLevelNodeValue": "Lightning-kabel",
    "DepartmentStock": [],
    "ArticleRole": "OTHER",
    "RetailItemCategoryGroup": "ZMAR",
    "RetailSalesStatus": "ACT",
    "WhlSaleItemCategoryGroup": "ZMAR",
    "ProductTaxonomy": [
      "Tjänster & Tillbehör",
      "Kablar & Anslutning",
      "Lightning-kabel"
    ],
    "ProductTaxonomyId": ["PT107", "PT287", "PT1034"],
    "OnlineRelevant": true,
    "OnlineRelevantB2B": true,
    "StockLastUpdated": null,
    "SellerName": "Elgiganten",
    "CheapestBItem": null,
    "AItem": null
  }]

###< ../../../../../matst80/bun-slask-sync/data/products_110.json