@cartId=2E64A8B2-91BD-44F7-98FC-C67FE8B6F000
@productId=764591
### Create cart

POST http://localhost:5170/cart
Content-Type: application/json

{
  "cartId": "{{cartId}}"
}

### Add item to cart
POST http://localhost:5170/cart/{{cartId}}/items
Content-Type: application/json

{
  "CartId": "{{cartId}}",
  "ProductId": "{{productId}}"
}

### Remove item from cart
DELETE http://localhost:5170/cart/{{cartId}}/items/7E64A8B2-91BD-44F7-98FC-C67FE8B6F0C8

### Get cart
GET http://localhost:5170/cart/{{cartId}}

### Get logged in user cart
GET http://localhost:5170/cart

### Get cart 
GET http://localhost:5170/cart/{{cartId}}

### Increase quantity of item in cart
POST http://localhost:5170/cart/{{cartId}}/items/{{productId}}/increase

### Decrease quantity of item in cart
POST http://localhost:5170/cart/{{cartId}}/items/{{productId}}/decrease