### Create cart

POST http://localhost:5170/cart
Content-Type: application/json

{
  "cartId": "7E64A8B2-91BD-44F7-98FC-C67FE8B6F0C7"
}

### Add item to cart
POST http://localhost:5170/cart/7E64A8B2-91BD-44F7-98FC-C67FE8B6F0C8/items
Content-Type: application/json

{
  "CartId": "7E64A8B2-91BD-44F7-98FC-C67FE8B6F0C7",
  "ProductId": "7E64A8B2-91BD-44F7-98FC-C67FE8B6F0C8"
}

### Remove item from cart
DELETE http://localhost:5170/cart/7E64A8B2-91BD-44F7-98FC-C67FE8B6F0C8/items/7E64A8B2-91BD-44F7-98FC-C67FE8B6F0C8

### Get cart
GET http://localhost:5170/cart/7E64A8B2-91BD-44F7-98FC-C67FE8B6F0C7

### Get logged in user cart
GET http://localhost:5170/cart

### Get cart by id
GET http://localhost:5170/cart/4

### Get cart 
GET http://localhost:5170/cart/f9bd58e7-13c5-41f5-96eb-3d0c8252894c